[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "brazilian_elections"
version = "0.0.1"
description = "Exploratory Data Analysis of Brazlian Electoral data of 2022"
authors = [
  { name = "Gabriel Sobral" },
]

readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    
]
requires-python = "~=3.10"


[tool.ruff]
line-length = 99
src = ["brazilian_elections"]
include = ["pyproject.toml", "brazilian_elections/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["brazilian_elections"]
force-sort-within-sections = true

